// <auto-generated />
using System;
using LIAnsureProtect.Modules.Claims.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIAnsureProtect.Modules.Claims.Infrastructure.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20260703134301_AddClaimOperations")]
    partial class AddClaimOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("claims")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIAnsureProtect.Modules.Claims.Domain.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedAdjusterUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("assigned_adjuster_user_id");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("claim_number");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at_utc");

                    b.Property<DateTime>("FiledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("filed_at_utc");

                    b.Property<DateTime>("IncidentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incident_at_utc");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("incident_type");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("PolicyEffectiveAtFiling")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("policy_effective_at_filing");

                    b.Property<DateTime>("PolicyExpirationAtFiling")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("policy_expiration_at_filing");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<decimal>("PolicyLimitAtFiling")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("policy_limit_at_filing");

                    b.Property<string>("PolicyNumberAtFiling")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("policy_number_at_filing");

                    b.Property<decimal>("PolicyRetentionAtFiling")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("policy_retention_at_filing");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdjusterUserId")
                        .HasDatabaseName("ix_claims_assigned_adjuster_user_id");

                    b.HasIndex("ClaimNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_claims_claim_number");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_claims_owner_user_id");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_claims_policy_id");

                    b.HasIndex("Status", "FiledAtUtc")
                        .HasDatabaseName("ix_claims_status_filed_at_utc");

                    b.ToTable("claims", "claims");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Claims.Domain.ClaimInformationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_answered");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at_utc");

                    b.Property<string>("RespondedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("responded_by_user_id");

                    b.Property<string>("ResponseText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("response_text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId", "RequestedAtUtc")
                        .HasDatabaseName("ix_claim_information_requests_claim_id_requested_at_utc");

                    b.ToTable("claim_information_requests", "claims");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Claims.Domain.ClaimTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entry_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId", "CreatedAtUtc")
                        .HasDatabaseName("ix_claim_timeline_entries_claim_id_created_at_utc");

                    b.ToTable("claim_timeline_entries", "claims");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Claims.Domain.ClaimWorkNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId", "CreatedAtUtc")
                        .HasDatabaseName("ix_claim_work_notes_claim_id_created_at_utc");

                    b.ToTable("claim_work_notes", "claims");
                });

            modelBuilder.Entity("LIAnsureProtect.Platform.Outbox.ModuleOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<DateTime?>("LastPublishAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_publish_attempt_at_utc");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_message_id");

                    b.Property<int>("PublishAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("publish_attempt_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc_created_at_utc");

                    b.HasIndex("ProcessedAtUtc", "FailedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_dispatch_retry");

                    b.ToTable("outbox_messages", "claims");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Claims.Domain.ClaimInformationRequest", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Claims.Domain.Claim", null)
                        .WithMany("InformationRequests")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Claims.Domain.ClaimTimelineEntry", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Claims.Domain.Claim", null)
                        .WithMany("TimelineEntries")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Claims.Domain.ClaimWorkNote", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Claims.Domain.Claim", null)
                        .WithMany("WorkNotes")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Claims.Domain.Claim", b =>
                {
                    b.Navigation("InformationRequests");

                    b.Navigation("TimelineEntries");

                    b.Navigation("WorkNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
