// <auto-generated />
using System;
using LIAnsureProtect.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIAnsureProtect.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubmissionDbContext))]
    [Migration("20260711201928_AddQuoteControlAssurance")]
    partial class AddQuoteControlAssurance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIAnsureProtect.Domain.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BoundAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bound_at_utc");

                    b.Property<string>("BoundByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("bound_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EffectiveDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date_utc");

                    b.Property<DateTime>("ExpirationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date_utc");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("policy_number");

                    b.Property<decimal>("Premium")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("premium");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("QuoteRiskTierAtBind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quote_risk_tier_at_bind");

                    b.Property<string>("QuoteStatusAtBind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quote_status_at_bind");

                    b.Property<string>("QuoteSubjectivitiesAtBind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_subjectivities_at_bind");

                    b.Property<decimal>("RequestedLimit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("requested_limit");

                    b.Property<decimal>("Retention")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("retention");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_policies_policy_number");

                    b.HasIndex("QuoteId")
                        .IsUnique()
                        .HasDatabaseName("ux_policies_quote_id");

                    b.HasIndex("OwnerUserId", "BoundAtUtc")
                        .HasDatabaseName("ix_policies_owner_user_id_bound_at_utc");

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Policies.PolicyBindingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BindingReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("binding_reference");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "CreatedAtUtc")
                        .HasDatabaseName("ix_policy_binding_attempts_policy_id_created_at_utc");

                    b.ToTable("policy_binding_attempts", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.ControlAssertion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssuranceState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assurance_state");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("ClaimedState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimed_state");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("control_type");

                    b.Property<string>("EvidenceReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence_reason");

                    b.Property<bool>("EvidenceRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_required");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<int>("QuoteVersion")
                        .HasColumnType("integer")
                        .HasColumnName("quote_version");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.Property<string>("VerifiedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "ControlType")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_control_assertions_quote_id_control_type");

                    b.ToTable("quote_control_assertions", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<string>("AcceptedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accepted_by_name");

                    b.Property<string>("AcceptedByTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accepted_by_title");

                    b.Property<string>("AcceptedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<string>("AssuranceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assurance_status");

                    b.Property<string>("AttestationWordingVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attestation_wording_version");

                    b.Property<DateTime?>("AttestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attested_at_utc");

                    b.Property<string>("AttestedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attested_by_name");

                    b.Property<string>("AttestedByTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attested_by_title");

                    b.Property<string>("AttestedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("attested_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EvidenceRequiredCount")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_required_count");

                    b.Property<int>("EvidenceSatisfiedCount")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_satisfied_count");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_user_id");

                    b.Property<decimal>("Premium")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("premium");

                    b.Property<string>("ReferralReasons")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referral_reasons");

                    b.Property<decimal>("RequestedLimit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("requested_limit");

                    b.Property<decimal>("Retention")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("retention");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_tier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_name");

                    b.Property<string>("Subjectivities")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subjectivities");

                    b.Property<bool>("SubjectivitiesAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("subjectivities_acknowledged");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid?>("SupersedesQuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_quote_id");

                    b.Property<string>("UnderwritingDecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("underwriting_decision_notes");

                    b.Property<string>("UnderwritingDecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("underwriting_decision_reason");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_quotes_submission_id");

                    b.HasIndex("OwnerUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_quotes_owner_user_id_created_at_utc");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_quotes_status_created_at_utc");

                    b.HasIndex("SubmissionId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_quotes_submission_id_version");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.QuoteRatingProviderAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("FailureCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_category");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<decimal?>("IndicatedLimit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("indicated_limit");

                    b.Property<decimal?>("IndicatedPremium")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("indicated_premium");

                    b.Property<decimal?>("IndicatedRetention")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("indicated_retention");

                    b.Property<string>("MarketDisposition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("market_disposition");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderQuoteNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_quote_number");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_reference");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("RequestPayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_payload_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_quote_rating_provider_attempts_quote_id_created_at_utc");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_quote_rating_provider_attempts_status_created_at_utc");

                    b.ToTable("quote_rating_provider_attempts", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.QuoteUnderwritingReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PremiumAfter")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("premium_after");

                    b.Property<decimal>("PremiumBefore")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("premium_before");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal>("RetentionAfter")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("retention_after");

                    b.Property<decimal>("RetentionBefore")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("retention_before");

                    b.Property<string>("ReviewedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reviewed_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_quote_underwriting_reviews_quote_id_created_at_utc");

                    b.ToTable("quote_underwriting_reviews", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("applicant_email");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("applicant_name");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_submissions_owner_user_id_created_at_utc");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Infrastructure.Persistence.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action_name");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("response_content_type");

                    b.Property<string>("ResponseLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("response_location");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_key");

                    b.HasIndex("Status", "CompletedAtUtc")
                        .HasDatabaseName("ix_idempotency_records_status_completed_at_utc");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<DateTime?>("LastPublishAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_publish_attempt_at_utc");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_message_id");

                    b.Property<int>("PublishAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("publish_attempt_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc_created_at_utc");

                    b.HasIndex("ProcessedAtUtc", "FailedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_dispatch_retry");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Policies.Policy", b =>
                {
                    b.HasOne("LIAnsureProtect.Domain.Quotes.Quote", null)
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Policies.PolicyBindingAttempt", b =>
                {
                    b.HasOne("LIAnsureProtect.Domain.Policies.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.ControlAssertion", b =>
                {
                    b.HasOne("LIAnsureProtect.Domain.Quotes.Quote", null)
                        .WithMany("ControlAssertions")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.Quote", b =>
                {
                    b.HasOne("LIAnsureProtect.Domain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.QuoteRatingProviderAttempt", b =>
                {
                    b.HasOne("LIAnsureProtect.Domain.Quotes.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.QuoteUnderwritingReview", b =>
                {
                    b.HasOne("LIAnsureProtect.Domain.Quotes.Quote", null)
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Domain.Quotes.Quote", b =>
                {
                    b.Navigation("ControlAssertions");
                });
#pragma warning restore 612, 618
        }
    }
}
