// <auto-generated />
using System;
using LIAnsureProtect.Modules.Underwriting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIAnsureProtect.Modules.Underwriting.Infrastructure.Migrations
{
    [DbContext(typeof(UnderwritingDbContext))]
    [Migration("20260630060413_CreateReferralOperations")]
    partial class CreateReferralOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("underwriting")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.AiUnderwritingReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdvisoryDisclaimer")
                        .HasColumnType("text")
                        .HasColumnName("advisory_disclaimer");

                    b.Property<string>("Citations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("citations");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ControlGaps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("control_gaps");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text")
                        .HasColumnName("executive_summary");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feedback");

                    b.Property<string>("InputSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_snapshot_hash");

                    b.Property<string>("Limitations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limitations");

                    b.Property<string>("NegativeRiskSignals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("negative_risk_signals");

                    b.Property<string>("OutputSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("output_schema_version");

                    b.Property<string>("PositiveRiskSignals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("positive_risk_signals");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_name");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedSubjectivityCandidates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_subjectivity_candidates");

                    b.Property<string>("SuggestedUnderwritingQuestions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_underwriting_questions");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_underwriting_reviews_quote_id_created_at_utc");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_underwriting_reviews_status_created_at_utc");

                    b.ToTable("ai_underwriting_reviews", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralFollowUpTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("completed_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<Guid>("QuoteReferralOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_referral_operation_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("QuoteReferralOperationId");

                    b.HasIndex("QuoteId", "CompletedAtUtc", "DueAtUtc")
                        .HasDatabaseName("ix_quote_referral_follow_up_tasks_quote_id_completed_due_at_utc");

                    b.ToTable("quote_referral_follow_up_tasks", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedUnderwriterUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("assigned_underwriter_user_id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_referral_operations_quote_id");

                    b.HasIndex("Status", "Priority", "DueAtUtc")
                        .HasDatabaseName("ix_quote_referral_operations_status_priority_due_at_utc");

                    b.ToTable("quote_referral_operations", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<Guid>("QuoteReferralOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_referral_operation_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("QuoteReferralOperationId");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_quote_referral_timeline_entries_quote_id_created_at_utc");

                    b.ToTable("quote_referral_timeline_entries", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralWorkNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<Guid>("QuoteReferralOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_referral_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("QuoteReferralOperationId");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_quote_referral_work_notes_quote_id_created_at_utc");

                    b.ToTable("quote_referral_work_notes", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.ReferralOperationProjectedMessage", b =>
                {
                    b.Property<Guid>("SourceOutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_outbox_message_id");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.HasKey("SourceOutboxMessageId");

                    b.ToTable("referral_operation_projected_messages", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralFollowUpTask", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", null)
                        .WithMany("Tasks")
                        .HasForeignKey("QuoteReferralOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralTimelineEntry", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", null)
                        .WithMany("TimelineEntries")
                        .HasForeignKey("QuoteReferralOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralWorkNote", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", null)
                        .WithMany("Notes")
                        .HasForeignKey("QuoteReferralOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Tasks");

                    b.Navigation("TimelineEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
