// <auto-generated />
using System;
using LIAnsureProtect.Modules.Underwriting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIAnsureProtect.Modules.Underwriting.Infrastructure.Migrations
{
    [DbContext(typeof(UnderwritingDbContext))]
    partial class UnderwritingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("underwriting")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.AiUnderwritingReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdvisoryDisclaimer")
                        .HasColumnType("text")
                        .HasColumnName("advisory_disclaimer");

                    b.Property<string>("Citations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("citations");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ControlGaps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("control_gaps");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text")
                        .HasColumnName("executive_summary");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feedback");

                    b.Property<string>("InputSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_snapshot_hash");

                    b.Property<string>("Limitations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limitations");

                    b.Property<string>("NegativeRiskSignals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("negative_risk_signals");

                    b.Property<string>("OutputSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("output_schema_version");

                    b.Property<string>("PositiveRiskSignals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("positive_risk_signals");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_name");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedSubjectivityCandidates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_subjectivity_candidates");

                    b.Property<string>("SuggestedUnderwritingQuestions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_underwriting_questions");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_underwriting_reviews_quote_id_created_at_utc");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_underwriting_reviews_status_created_at_utc");

                    b.ToTable("ai_underwriting_reviews", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Evidence.Documents.QuoteEvidenceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdvisoryFindingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("advisory_findings_json");

                    b.Property<string>("AssessmentVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assessment_version");

                    b.Property<string>("ClaimConsistencyStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("claim_consistency_status");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("EvidenceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_request_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PlausibilityStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plausibility_status");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("ScanResultCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scan_result_code");

                    b.Property<string>("ScanResultReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("scan_result_reason");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("PendingScan")
                        .HasColumnName("scan_status");

                    b.Property<DateTime?>("ScannedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at_utc");

                    b.Property<string>("ScannerProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scanner_provider_name");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_evidence_documents_storage_key");

                    b.HasIndex("EvidenceRequestId", "UploadedAtUtc")
                        .HasDatabaseName("ix_quote_evidence_documents_request_uploaded_at_utc");

                    b.HasIndex("OwnerUserId", "EvidenceRequestId")
                        .HasDatabaseName("ix_quote_evidence_documents_owner_request");

                    b.HasIndex("ScanStatus", "UploadedAtUtc")
                        .HasDatabaseName("ix_quote_evidence_documents_scan_status_uploaded_at_utc");

                    b.ToTable("quote_evidence_documents", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Evidence.QuoteAssuranceProjectedMessage", b =>
                {
                    b.Property<Guid>("SourceOutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_outbox_message_id");

                    b.Property<DateTime>("ProjectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projected_at_utc");

                    b.HasKey("SourceOutboxMessageId");

                    b.ToTable("quote_assurance_projected_messages", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Evidence.QuoteEvidenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<string>("AcceptedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<string>("AttachmentContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attachment_content_type");

                    b.Property<string>("AttachmentFileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("attachment_file_name");

                    b.Property<long?>("AttachmentSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("attachment_size_bytes");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<string>("CancelledByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("RemediationGuidance")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("remediation_guidance");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at_utc");

                    b.Property<string>("RespondedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("responded_by_user_id");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("respondent_name");

                    b.Property<string>("RespondentTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("respondent_title");

                    b.Property<string>("ResponseText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("response_text");

                    b.Property<string>("ReviewDecision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("NotReviewed")
                        .HasColumnName("review_decision");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_notes");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_reason");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Status", "DueAtUtc")
                        .HasDatabaseName("ix_quote_evidence_requests_owner_status_due_at_utc");

                    b.HasIndex("QuoteId", "Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_quote_evidence_requests_quote_status_updated_at_utc");

                    b.ToTable("quote_evidence_requests", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Evidence.QuoteEvidenceRequestReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<int>("CleanDocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("clean_document_count");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("document_count");

                    b.Property<Guid>("EvidenceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_request_id");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("RemediationGuidance")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("remediation_guidance");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRequestId", "ReviewedAtUtc")
                        .HasDatabaseName("ix_quote_evidence_request_reviews_request_reviewed_at_utc");

                    b.HasIndex("QuoteId", "ReviewedAtUtc")
                        .HasDatabaseName("ix_quote_evidence_request_reviews_quote_reviewed_at_utc");

                    b.ToTable("quote_evidence_request_reviews", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralFollowUpTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("completed_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<Guid>("QuoteReferralOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_referral_operation_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("QuoteReferralOperationId");

                    b.HasIndex("QuoteId", "CompletedAtUtc", "DueAtUtc")
                        .HasDatabaseName("ix_quote_referral_follow_up_tasks_quote_id_completed_due_at_utc");

                    b.ToTable("quote_referral_follow_up_tasks", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedUnderwriterUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("assigned_underwriter_user_id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_referral_operations_quote_id");

                    b.HasIndex("Status", "Priority", "DueAtUtc")
                        .HasDatabaseName("ix_quote_referral_operations_status_priority_due_at_utc");

                    b.ToTable("quote_referral_operations", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<Guid>("QuoteReferralOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_referral_operation_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("QuoteReferralOperationId");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_quote_referral_timeline_entries_quote_id_created_at_utc");

                    b.ToTable("quote_referral_timeline_entries", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralWorkNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<Guid>("QuoteReferralOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_referral_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("QuoteReferralOperationId");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_quote_referral_work_notes_quote_id_created_at_utc");

                    b.ToTable("quote_referral_work_notes", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.ReferralOperationProjectedMessage", b =>
                {
                    b.Property<Guid>("SourceOutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_outbox_message_id");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.HasKey("SourceOutboxMessageId");

                    b.ToTable("referral_operation_projected_messages", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Platform.Outbox.ModuleOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<DateTime?>("LastPublishAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_publish_attempt_at_utc");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_message_id");

                    b.Property<int>("PublishAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("publish_attempt_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc_created_at_utc");

                    b.HasIndex("ProcessedAtUtc", "FailedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_dispatch_retry");

                    b.ToTable("outbox_messages", "underwriting");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Evidence.QuoteEvidenceRequestReview", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Underwriting.Domain.Evidence.QuoteEvidenceRequest", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralFollowUpTask", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", null)
                        .WithMany("Tasks")
                        .HasForeignKey("QuoteReferralOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralTimelineEntry", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", null)
                        .WithMany("TimelineEntries")
                        .HasForeignKey("QuoteReferralOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralWorkNote", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", null)
                        .WithMany("Notes")
                        .HasForeignKey("QuoteReferralOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.Referrals.QuoteReferralOperation", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Tasks");

                    b.Navigation("TimelineEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
