// <auto-generated />
using System;
using LIAnsureProtect.Modules.Underwriting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIAnsureProtect.Modules.Underwriting.Infrastructure.Migrations
{
    [DbContext(typeof(UnderwritingDbContext))]
    partial class UnderwritingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("underwriting")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIAnsureProtect.Modules.Underwriting.Domain.AiUnderwritingReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdvisoryDisclaimer")
                        .HasColumnType("text")
                        .HasColumnName("advisory_disclaimer");

                    b.Property<string>("Citations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("citations");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ControlGaps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("control_gaps");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text")
                        .HasColumnName("executive_summary");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feedback");

                    b.Property<string>("InputSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_snapshot_hash");

                    b.Property<string>("Limitations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limitations");

                    b.Property<string>("NegativeRiskSignals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("negative_risk_signals");

                    b.Property<string>("OutputSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("output_schema_version");

                    b.Property<string>("PositiveRiskSignals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("positive_risk_signals");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_name");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedSubjectivityCandidates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_subjectivity_candidates");

                    b.Property<string>("SuggestedUnderwritingQuestions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_underwriting_questions");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_underwriting_reviews_quote_id_created_at_utc");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_underwriting_reviews_status_created_at_utc");

                    b.ToTable("ai_underwriting_reviews", "underwriting");
                });
#pragma warning restore 612, 618
        }
    }
}
