// <auto-generated />
using System;
using LIAnsureProtect.Modules.Notifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIAnsureProtect.Modules.Notifications.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260715182038_AddNotificationLifecycle")]
    partial class AddNotificationLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIAnsureProtect.Modules.Notifications.Domain.NotificationInboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audience");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("HistoricalAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("historical_at_utc");

                    b.Property<string>("HistoricalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("historical_reason");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Active")
                        .HasColumnName("lifecycle_state");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid?>("ReplacementQuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("replacement_quote_id");

                    b.Property<int?>("ReplacementQuoteVersion")
                        .HasColumnType("integer")
                        .HasColumnName("replacement_quote_version");

                    b.Property<Guid>("SourceOutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_outbox_message_id");

                    b.Property<string>("SubjectReferenceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_reference_id");

                    b.Property<string>("SubjectReferenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_reference_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SourceOutboxMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_inbox_entries_source_outbox_message_id");

                    b.HasIndex("RecipientUserId", "ReadAtUtc")
                        .HasDatabaseName("ix_notification_inbox_entries_recipient_read");

                    b.HasIndex("RecipientUserId", "LifecycleState", "ReadAtUtc")
                        .HasDatabaseName("ix_notification_inbox_entries_recipient_lifecycle_read");

                    b.ToTable("notification_inbox_entries", "notifications");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Notifications.Domain.TeamNotificationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audience");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("HistoricalAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("historical_at_utc");

                    b.Property<string>("HistoricalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("historical_reason");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Active")
                        .HasColumnName("lifecycle_state");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("ReplacementQuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("replacement_quote_id");

                    b.Property<int?>("ReplacementQuoteVersion")
                        .HasColumnType("integer")
                        .HasColumnName("replacement_quote_version");

                    b.Property<Guid>("SourceOutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_outbox_message_id");

                    b.Property<string>("SubjectReferenceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_reference_id");

                    b.Property<string>("SubjectReferenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_reference_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SourceOutboxMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_notification_entries_source_outbox_message_id");

                    b.HasIndex("Audience", "CreatedAtUtc")
                        .HasDatabaseName("ix_team_notification_entries_audience_created_at_utc");

                    b.HasIndex("Audience", "LifecycleState", "CreatedAtUtc")
                        .HasDatabaseName("ix_team_notification_entries_audience_lifecycle_created_at_utc");

                    b.ToTable("team_notification_entries", "notifications");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Notifications.Domain.TeamNotificationReadReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid>("TeamNotificationEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_notification_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamNotificationEntryId", "RecipientUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_team_notification_read_receipts_entry_recipient");

                    b.ToTable("team_notification_read_receipts", "notifications");
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Notifications.Domain.TeamNotificationReadReceipt", b =>
                {
                    b.HasOne("LIAnsureProtect.Modules.Notifications.Domain.TeamNotificationEntry", null)
                        .WithMany("ReadReceipts")
                        .HasForeignKey("TeamNotificationEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIAnsureProtect.Modules.Notifications.Domain.TeamNotificationEntry", b =>
                {
                    b.Navigation("ReadReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
